version: '3.8'

services:
  php:
    build:
      context: .
    volumes:
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
    ports:
      - "8888:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
